"""
Step 5: GitHub Pusher

Creates a new GitHub repository, commits the generated scaffold as a
single commit using the Git tree API, and opens a pull request.
"""

import os
from github import Github, GithubException, InputGitTreeElement


async def push_to_github(org_id: str, intent: dict, file_tree: dict[str, str]) -> dict:
    token = _get_github_token(org_id)
    gh = Github(token)

    repo_name = intent.get("repo_name_hint", "new-service-infra")
    org_login = _get_org_login(org_id)

    # Create repo — try org first, fall back to personal account
    try:
        try:
            owner = gh.get_organization(org_login)
        except GithubException:
            owner = gh.get_user()  # authenticated user — has create_repo
        repo = owner.create_repo(
            name=repo_name,
            description="Scaffolded by ControlPlane AI",
            private=True,
            auto_init=True,
        )
    except GithubException as e:
        raise RuntimeError(f"Failed to create repo: {e}")

    # Build a single commit from the full file tree using the Git tree API
    default_branch = repo.get_branch(repo.default_branch)
    base_sha = default_branch.commit.sha
    base_tree = repo.get_git_commit(base_sha).tree

    tree_elements = [
        InputGitTreeElement(
            path=path,
            mode="100644",
            type="blob",
            content=content,
        )
        for path, content in file_tree.items()
    ]

    new_tree = repo.create_git_tree(tree_elements, base_tree)
    new_commit = repo.create_git_commit(
        message="chore: initial infrastructure scaffold (ControlPlane AI)",
        tree=new_tree,
        parents=[repo.get_git_commit(base_sha)],
    )

    # Create scaffold branch pointing at the new commit
    branch_name = "controlplane/initial-scaffold"
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=new_commit.sha,
    )

    # Open PR
    pr = repo.create_pull(
        title="chore: initial infrastructure scaffold (ControlPlane AI)",
        body=(
            "This PR was generated by **ControlPlane AI**.\n\n"
            "Review the scaffold, adjust as needed, and merge to get started.\n\n"
            f"**Template:** `{intent.get('service_type', 'unknown')}`\n"
            f"**Environments:** {', '.join(intent.get('environments', []))}\n"
        ),
        head=branch_name,
        base=repo.default_branch,
    )

    return {"repo_url": repo.html_url, "pr_url": pr.html_url}


def _get_github_token(org_id: str) -> str:
    # TODO: fetch per-org token from secrets store
    return os.environ["GITHUB_TOKEN"]


def _get_org_login(org_id: str) -> str:
    # TODO: look up org GitHub login from DB
    return os.environ["GITHUB_ORG_LOGIN"]
