"""
Step 5: GitHub Pusher

Creates a new GitHub repository, commits the generated scaffold, and opens
a pull request.

Uses only the Contents API (PUT /contents/{path}) and the Refs API
(POST /git/refs) — the two endpoints that reliably work with standard OAuth
tokens on brand-new repos. The git Trees/Blobs API and GraphQL
createCommitOnBranch both returned errors on fresh repos.
"""

import asyncio
import secrets

from github import Github, GithubException


def _is_name_conflict(exc: GithubException) -> bool:
    errors = exc.data.get("errors", []) if isinstance(exc.data, dict) else []
    return any(e.get("message") == "name already exists on this account" for e in errors)


async def push_to_github(
    org_id: str,
    intent: dict,
    file_tree: dict[str, str],
    github_token: str,
    github_org_login: str,
) -> dict:
    gh = Github(github_token)
    base_name = intent.get("repo_name_hint", "new-service-infra")

    # Resolve owner — org workspace first, fall back to authenticated user
    try:
        owner = gh.get_organization(github_org_login)
    except GithubException:
        owner = gh.get_user()

    # Create repo — retry with hex suffix on name conflict
    repo = None
    repo_name = base_name
    for attempt in range(5):
        try:
            repo = owner.create_repo(
                name=repo_name,
                description="Scaffolded by ControlPlane AI",
                private=True,
                auto_init=True,
            )
            break
        except GithubException as e:
            if _is_name_conflict(e) and attempt < 4:
                repo_name = f"{base_name}-{secrets.token_hex(3)}"
            else:
                raise RuntimeError(f"Failed to create repo '{repo_name}': {e}") from e

    # Wait for auto_init commit to propagate
    default_branch = repo.default_branch
    head_sha = None
    for attempt in range(10):
        try:
            ref = repo.get_git_ref(f"heads/{default_branch}")
            head_sha = ref.object.sha
            break
        except GithubException:
            if attempt == 9:
                raise RuntimeError("Timed out waiting for initial commit")
            await asyncio.sleep(2)

    # Create PR branch from default branch HEAD (Refs API — distinct from Trees API)
    branch_name = "controlplane/initial-scaffold"
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=head_sha)

    # Push every file via Contents API.
    # Retries on transient 404s (branch ref lag) and falls back to update_file
    # on 422 (file already exists from auto_init, e.g. README.md).
    # Failures are collected and logged but don't abort the push — the PR is
    # always created so the user gets a link even if a few files missed.
    import time

    def _push_one(path: str, content: str) -> str | None:
        """Returns error string on failure, None on success."""
        for attempt in range(4):
            try:
                repo.create_file(
                    path=path,
                    message=f"chore: add {path}",
                    content=content,
                    branch=branch_name,
                )
                return None
            except GithubException as e:
                if e.status == 422:
                    # File already exists — update instead
                    try:
                        existing = repo.get_contents(path, ref=branch_name)
                        repo.update_file(
                            path=path,
                            message=f"chore: add {path}",
                            content=content,
                            sha=existing.sha,
                            branch=branch_name,
                        )
                        return None
                    except GithubException as ue:
                        return f"{path}: update failed ({ue.status})"
                elif e.status in (404, 409, 503) and attempt < 3:
                    time.sleep(2 * (attempt + 1))
                else:
                    return f"{path}: {e.status} {e.data}"
        return f"{path}: max retries exceeded"

    def _push_files():
        failures = []
        for path, content in file_tree.items():
            err = _push_one(path, content)
            if err:
                print(f"[github_pusher] WARNING: {err}")
                failures.append(err)
        return failures

    failures = await asyncio.to_thread(_push_files)
    if failures:
        print(f"[github_pusher] {len(failures)} file(s) failed: {failures}")

    # Open PR
    pr = repo.create_pull(
        title="chore: initial infrastructure scaffold (ControlPlane AI)",
        body=(
            "This PR was generated by **ControlPlane AI**.\n\n"
            "Review the scaffold, adjust as needed, and merge to get started.\n\n"
            f"**Stack:** `{intent.get('stack', 'terraform')}`\n"
            f"**Cloud:** `{intent.get('cloud', 'unknown')}`\n"
            f"**Environments:** {', '.join(intent.get('environments', []))}\n"
        ),
        head=branch_name,
        base=default_branch,
    )

    return {"repo_url": repo.html_url, "pr_url": pr.html_url}
