"""
Step 5: GitHub Pusher

Creates a new GitHub repository, commits the generated scaffold as a
single commit using the Git tree API, and opens a pull request.
"""

import asyncio
import secrets

from github import Github, GithubException, InputGitTreeElement


def _is_name_conflict(exc: GithubException) -> bool:
    errors = exc.data.get("errors", []) if isinstance(exc.data, dict) else []
    return any(e.get("message") == "name already exists on this account" for e in errors)


async def push_to_github(
    org_id: str,
    intent: dict,
    file_tree: dict[str, str],
    github_token: str,
    github_org_login: str,
) -> dict:
    gh = Github(github_token)

    base_name = intent.get("repo_name_hint", "new-service-infra")

    # Resolve owner — org workspace first, fall back to authenticated user
    try:
        owner = gh.get_organization(github_org_login)
    except GithubException:
        owner = gh.get_user()

    # Try base name, then base-XXXX with a random hex suffix on conflict
    repo = None
    repo_name = base_name
    for attempt in range(5):
        try:
            repo = owner.create_repo(
                name=repo_name,
                description="Scaffolded by ControlPlane AI",
                private=True,
                auto_init=True,
            )
            break
        except GithubException as e:
            if _is_name_conflict(e) and attempt < 4:
                repo_name = f"{base_name}-{secrets.token_hex(3)}"
            else:
                raise RuntimeError(f"Failed to create repo '{repo_name}': {e}") from e

    # GitHub propagates the initial commit asynchronously after auto_init.
    # Retry fetching the default branch until it resolves (usually < 3s).
    base_sha = None
    for attempt in range(8):
        try:
            default_branch = repo.get_branch(repo.default_branch)
            base_sha = default_branch.commit.sha
            break
        except GithubException:
            if attempt == 7:
                raise RuntimeError("Timed out waiting for initial commit after repo creation")
            await asyncio.sleep(1.5)

    base_tree = repo.get_git_commit(base_sha).tree

    tree_elements = [
        InputGitTreeElement(
            path=path,
            mode="100644",
            type="blob",
            content=content,
        )
        for path, content in file_tree.items()
    ]

    new_tree = repo.create_git_tree(tree_elements, base_tree)
    new_commit = repo.create_git_commit(
        message="chore: initial infrastructure scaffold (ControlPlane AI)",
        tree=new_tree,
        parents=[repo.get_git_commit(base_sha)],
    )

    # Create scaffold branch pointing at the new commit
    branch_name = "controlplane/initial-scaffold"
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=new_commit.sha,
    )

    # Open PR
    pr = repo.create_pull(
        title="chore: initial infrastructure scaffold (ControlPlane AI)",
        body=(
            "This PR was generated by **ControlPlane AI**.\n\n"
            "Review the scaffold, adjust as needed, and merge to get started.\n\n"
            f"**Template:** `{intent.get('service_type', 'unknown')}`\n"
            f"**Environments:** {', '.join(intent.get('environments', []))}\n"
        ),
        head=branch_name,
        base=repo.default_branch,
    )

    return {"repo_url": repo.html_url, "pr_url": pr.html_url}
